# Generated by Django 6.1 on 2026-09-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('sql', models.TextField(help_text='Equivalent SQL for the operation performed.')),
                ('orm', models.TextField(help_text='The Django ORM call the view made.')),
                ('http', models.CharField(help_text='HTTP method and path.', max_length=120)),
                ('rows_affected', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
