# Generated by Django 6.1 on 2026-10-05 17:23

import students.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_operationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='status',
            field=models.CharField(choices=[('OK', 'Succeeded'), ('REJECTED', 'Rejected by a constraint')], default='OK', max_length=10),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='tag',
            field=models.CharField(blank=True, help_text='Machine-readable marker used to auto-check exercises.', max_length=32),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A student with this email already exists — the UNIQUE constraint refused the row.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, validators=[students.validators.validate_not_numeric]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=16, validators=[students.validators.validate_phone]),
        ),
    ]
