"""The file-level path a single operation takes through the project.

Students can see *that* an operation worked, but not *where* it went. This
module describes, for each operation, which project file handles it, what that
file does, and how control is handed to the next one — so the Simulation can
show the route through the codebase alongside the SQL.

It also makes an easily-missed point explicit: running a CRUD operation does
not modify any source file. The code files are **traversed**; the only thing
that **changes** is the database. Each step therefore carries an `effect`:

    ``routes``    the file decided where to go next
    ``runs``      the file executed logic
    ``reads``     the file was read from, unchanged
    ``writes``    the file's contents changed  ← only ever the database
    ``renders``   the file produced the HTML sent back

Nothing here is generated by inspecting a live request; the traces are written
by hand to match the code, and `test_trace.py` checks that every file and
symbol named actually exists.
"""

from dataclasses import dataclass

DB_FILE = 'db.sqlite3'


@dataclass(frozen=True)
class Step:
    """One file in the path an operation takes."""

    file: str        #: path relative to the project root
    symbol: str      #: the function, class or pattern involved
    role: str        #: a two-word label, e.g. 'URL routing'
    detail: str      #: what happens in this file
    handoff: str     #: how control reaches the next file ('' for the last step)
    effect: str      #: routes | runs | reads | writes | renders

    @property
    def changed(self):
        return self.effect == 'writes'


# ---------------------------------------------------------------------------
# Steps shared by every route
# ---------------------------------------------------------------------------

def _project_urls(prefix='simulation/'):
    return Step(
        file='studentproject/urls.py',
        symbol=f"path('{prefix}', include('students.urls'))",
        role='URL routing',
        detail='Django works through the project URLconf from the top. This pattern '
               'matches the start of the path and strips it off.',
        handoff=f'include() hands the rest of the path to the students app',
        effect='routes',
    )


def _app_urls(pattern, view_name):
    return Step(
        file='students/urls.py',
        symbol=pattern,
        role='URL routing',
        detail='The remaining part of the path is matched against this app\'s patterns. '
               'The first one that matches names the view to call.',
        handoff=f'calls {view_name}',
        effect='routes',
    )


def _db(effect, detail):
    return Step(
        file=DB_FILE,
        symbol='table: students',
        role='Database' if effect == 'writes' else 'Database (read only)',
        detail=detail,
        handoff='returns control to the view',
        effect=effect,
    )


def _log_step(after_read=False):
    """The lab's own bookkeeping write.

    Note that the file named here is the database, not `students/models.py`.
    `OperationLog.record()` is defined in models.py, but calling it changes a
    table, not the source file — which is the whole point this panel is making.
    """
    detail = ('The operation itself changed nothing, but the lab records that you ran '
              'it, so the Statement log and the Exercises checker can see it.'
              if after_read else
              'The statement is also appended to the log table, which is what the '
              'Statement log panel and the Exercises checker read.')
    return Step(
        file=DB_FILE,
        symbol='table: students_operationlog  ·  via OperationLog.record() in students/models.py',
        role='Statement log',
        detail=detail,
        handoff='the view returns its response',
        effect='writes',
    )


def _template(name, detail):
    return Step(
        file=f'students/templates/students/{name}',
        symbol='{% extends \'lab/base.html\' %}',
        role='Template',
        detail=detail,
        handoff='',
        effect='renders',
    )


def _validation_steps():
    return [
        Step(
            file='students/forms.py',
            symbol='StudentForm.clean_name() · clean_email() · clean_phone() · clean()',
            role='Form validation',
            detail='Each field is cleaned by its own method, then the form-wide clean() '
                   'runs last for rules that span two fields. No SQL has been sent yet.',
            handoff='field validators declared on the model run as part of this',
            effect='runs',
        ),
        Step(
            file='students/validators.py',
            symbol='validate_phone() · validate_not_numeric()',
            role='Field validators',
            detail='These are attached to the model fields, so the same rules apply to '
                   'the form, the REST API and the admin alike.',
            handoff='if everything is valid, the view calls form.save()',
            effect='runs',
        ),
    ]


# ---------------------------------------------------------------------------
# One trace per operation
# ---------------------------------------------------------------------------

def for_create():
    return [
        _project_urls(),
        _app_urls("path('add/', views.student_create, name='create')",
                  'views.student_create()'),
        Step(
            file='students/views.py',
            symbol='student_create()',
            role='View',
            detail='Receives the POST and builds a StudentForm from request.POST.',
            handoff='calls form.is_valid(), which runs the form below',
            effect='runs',
        ),
        *_validation_steps(),
        Step(
            file='students/models.py',
            symbol='Student',
            role='Model / ORM',
            detail='form.save() asks the ORM to write the instance. The ORM turns it '
                   'into an INSERT and sends the values as parameters.',
            handoff='the ORM opens the database file',
            effect='runs',
        ),
        _db('writes', 'The row is inserted and the database assigns the primary key. '
                      'This is the only file on the whole path whose contents change.'),
        _log_step(),
        _template('simulator.html',
                  'After the redirect, the simulator renders the new state of the table.'),
    ]


def for_read(single=False):
    pattern = ("path('<int:pk>/', views.student_detail, name='detail')" if single
               else "path('', views.simulator, name='simulator')")
    view = 'views.student_detail()' if single else 'views.simulator()'
    return [
        _project_urls(),
        _app_urls(pattern, view),
        Step(
            file='students/views.py',
            symbol='student_detail()' if single else 'simulator()',
            role='View',
            detail=('get_object_or_404() looks the row up by its primary key.' if single
                    else 'Builds a queryset, applying the filter from the ?q= parameter '
                         'if one was given.'),
            handoff='evaluating the queryset sends the SELECT',
            effect='runs',
        ),
        Step(
            file='students/models.py',
            symbol='Student',
            role='Model / ORM',
            detail=('The model class defines the columns. The query itself — '
                    'Student.objects.get(pk=…) — is served by the manager Django '
                    'attaches to it.' if single else
                    'The model class defines the columns. The query itself — '
                    'Student.objects.all() / .filter(…) — is served by the manager '
                    'Django attaches to it.'),
            handoff='the ORM reads from the database file',
            effect='runs',
        ),
        _db('reads', 'Rows are read out. Nothing is modified — a SELECT leaves both the '
                     'table and the file unchanged.'),
        _log_step(after_read=True),
        _template('student_detail.html' if single else 'simulator.html',
                  'The rows are looped over in the template and rendered as a table.'),
    ]


def for_update(pk=None):
    target = pk if pk is not None else '<id>'
    return [
        _project_urls(),
        _app_urls("path('<int:pk>/edit/', views.student_update, name='update')",
                  'views.student_update()'),
        Step(
            file='students/views.py',
            symbol='student_update()',
            role='View',
            detail=f'Loads row {target} and binds the POST data to it with '
                   'StudentForm(request.POST, instance=student) — which is what makes '
                   'this an UPDATE rather than an INSERT.',
            handoff='calls form.is_valid()',
            effect='runs',
        ),
        *_validation_steps(),
        Step(
            file='students/models.py',
            symbol='Student',
            role='Model / ORM',
            detail='obj.save() is inherited from django.db.models.Model, not written '
                   'in this file. Because the instance already carries a primary key, '
                   'it emits UPDATE … WHERE id = … rather than INSERT.',
            handoff='the ORM writes to the database file',
            effect='runs',
        ),
        _db('writes', f'The columns of row {target} are rewritten in place. The primary '
                      'key is untouched, and no new row is created.'),
        _log_step(),
        _template('simulator.html', 'The simulator re-renders with the updated row.'),
    ]


def for_delete(pk=None):
    target = pk if pk is not None else '<id>'
    return [
        _project_urls(),
        _app_urls("path('<int:pk>/delete/', views.student_delete, name='delete')",
                  'views.student_delete()'),
        Step(
            file='students/views.py',
            symbol='student_delete()',
            role='View',
            detail='A GET renders the confirmation page and changes nothing. Only a POST '
                   'reaches the delete itself.',
            handoff='calls student.delete()',
            effect='runs',
        ),
        Step(
            file='students/models.py',
            symbol='Student',
            role='Model / ORM',
            detail='obj.delete() is inherited from django.db.models.Model, not written '
                   'in this file. It emits DELETE … WHERE id = … for this single row.',
            handoff='the ORM writes to the database file',
            effect='runs',
        ),
        _db('writes', f'Row {target} is removed. The key counter does not move back, so '
                      'the identifier is retired and never reissued.'),
        _log_step(),
        _template('simulator.html', 'The simulator re-renders with one row fewer.'),
    ]


def for_terminal(writes=True, mode='sql'):
    """The path a typed terminal command takes — a different route to the same model."""
    parser = 'parse_sql()' if mode == 'sql' else 'parse_orm()'
    return [
        _project_urls(),
        _app_urls("path('terminal/run/', views.terminal_run, name='terminal_run')",
                  'views.terminal_run()'),
        Step(
            file='students/views.py',
            symbol='terminal_run()',
            role='View',
            detail='Reads the typed command out of the JSON body. It does not interpret '
                   'the command itself.',
            handoff='calls terminal.execute(command, mode)',
            effect='runs',
        ),
        Step(
            file='students/terminal/parsers.py',
            symbol=parser,
            role='Parser',
            detail='Your text is matched against explicit patterns and turned into a '
                   'Command object. Nothing is evaluated and no raw SQL is built — this '
                   'is why only the students table can ever be reached.',
            handoff='returns a Command to the engine',
            effect='runs',
        ),
        Step(
            file='students/terminal/engine.py',
            symbol='execute() → _run()',
            role='Engine',
            detail='Carries the Command out through the ORM, and renders the equivalent '
                   'statement in the other language for display.',
            handoff='calls into the model',
            effect='runs',
        ),
        Step(
            file='students/models.py',
            symbol='Student',
            role='Model / ORM',
            detail='The same model the forms use. The terminal is a different entrance '
                   'to exactly the same code path.',
            handoff='the ORM reaches the database file',
            effect='runs',
        ),
        _db('writes' if writes else 'reads',
            'The statement is applied and the file changes.' if writes
            else 'Rows are read out; nothing is modified.'),
        _log_step(after_read=not writes),
        _template('terminal.html',
                  'The JSON response is rendered line by line into the console by the '
                  'page\'s JavaScript.'),
    ]


#: Lookup used by the views and the terminal, keyed by the log tag.
BY_TAG = {
    'read_all': lambda: for_read(single=False),
    'read_filtered': lambda: for_read(single=False),
    'read_one': lambda: for_read(single=True),
    'create': for_create,
    'create_rejected': for_create,
    'update': for_update,
    'update_rejected': for_update,
    'delete': for_delete,
}


def for_tag(tag):
    """The trace matching a statement-log tag, or an empty list if unknown."""
    builder = BY_TAG.get(tag)
    return builder() if builder else []
