# Generated by Django 6.1 on 2026-10-05 17:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Optional.', max_length=254)),
                ('rating', models.PositiveSmallIntegerField(help_text='1 (poor) to 5 (excellent).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PRE', 'Pretest'), ('POST', 'Posttest')], max_length=4)),
                ('score', models.PositiveIntegerField(help_text='Number of questions answered correctly.')),
                ('total', models.PositiveIntegerField(help_text='Number of questions in the test.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PRE', 'Pretest'), ('POST', 'Posttest')], help_text='Which test this question appears in.', max_length=4)),
                ('order', models.PositiveIntegerField(default=1, help_text='Position of the question within its test.')),
                ('text', models.CharField(max_length=300)),
                ('explanation', models.TextField(blank=True, help_text='Shown after submission to explain the correct answer.')),
            ],
            options={
                'ordering': ['stage', 'order'],
                'constraints': [models.UniqueConstraint(fields=('stage', 'order'), name='unique_question_order')],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lab.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lab.quizattempt')),
            ],
            options={
                'ordering': ['question__order'],
            },
        ),
    ]
