"""Static written content for the virtual lab.

Keeping the structured content here rather than inside templates means the
templates stay as pure presentation, and an instructor can edit the wording of
the experiment in one Python file without touching HTML.

>>> EDIT ME: `CONTRIBUTORS` below contains placeholder names. Replace them with
>>> your team's real details before submitting.
"""


# ---------------------------------------------------------------------------
# Masthead, breadcrumb and footer  >>> EDIT ME <<<
#
# The interface follows the Virtual Labs house style. The institution shown in
# the masthead and the breadcrumb trail are configured here rather than
# hard-coded into the template, so they can be changed without touching HTML.
# ---------------------------------------------------------------------------

#: The experiment's own title, shown centred at the top of every page.
EXPERIMENT_TITLE = 'Performing CRUD Operations on a Relational Database using Django'

#: Shown at the left of the masthead.
#: These are plain text, set here rather than in the template. The institution's
#: own logo file is deliberately not bundled — see the note in the README.
INSTITUTION_NAME = 'Somaiya'
INSTITUTION_SUBTITLE = 'Vidyavihar University'
INSTITUTION_LINE_1 = 'K J Somaiya School of Engineering'
INSTITUTION_LINE_2 = '(formerly K J Somaiya College of Engineering)'
INSTITUTION_URL = 'https://kjsce.somaiya.edu/en'

#: The breadcrumb trail. Every entry is a real link — `url` is either a plain
#: path or the name of a URL pattern, resolved in lab/context_processors.py.
BREADCRUMB = [
    {'label': 'Computer Engineering', 'url_name': 'lab:aim'},
    {'label': 'Database Systems Lab', 'url_name': 'lab:aim'},
    {'label': 'Experiments', 'url_name': 'lab:aim'},
]

#: Footer columns. Links are the experiment's own — the official Virtual Labs
#: portal links are deliberately not reproduced here, because this is a course
#: project and not an official Virtual Labs deployment.
FOOTER_COLUMNS = [
    {
        'heading': 'This Experiment',
        'links': [
            {'label': 'Aim', 'url_name': 'lab:aim'},
            {'label': 'Theory', 'url_name': 'lab:theory'},
            {'label': 'Simulation', 'url_name': 'students:simulator'},
            {'label': 'References', 'url_name': 'lab:references'},
        ],
    },
    {
        'heading': 'Take Part',
        'links': [
            {'label': 'Pretest', 'url_name': 'lab:pretest'},
            {'label': 'Exercises', 'url_name': 'lab:exercises'},
            {'label': 'Posttest', 'url_name': 'lab:posttest'},
            {'label': 'Feedback', 'url_name': 'lab:feedback'},
        ],
    },
    {
        'heading': 'Built With',
        'links': [
            {'label': 'Django', 'url': 'https://www.djangoproject.com/'},
            {'label': 'Django REST Framework', 'url': 'https://www.django-rest-framework.org/'},
            {'label': 'SQLite', 'url': 'https://www.sqlite.org/'},
            {'label': 'REST API (this lab)', 'url': '/api/students/'},
        ],
    },
]

FOOTER_NOTE = ('Database Systems Virtual Lab · Experiment 1 · a course project, '
               'not an official Virtual Labs deployment.')

# ---------------------------------------------------------------------------
# Theory
# ---------------------------------------------------------------------------

CRUD_MAPPING = [
    {
        'crud': 'CREATE',
        'sql': 'INSERT',
        'http': 'POST',
        'orm': 'Model.objects.create(...)',
        'meaning': 'Add a new row to the table.',
    },
    {
        'crud': 'READ',
        'sql': 'SELECT',
        'http': 'GET',
        'orm': 'Model.objects.all() / .get(pk=...)',
        'meaning': 'Retrieve existing rows without changing them.',
    },
    {
        'crud': 'UPDATE',
        'sql': 'UPDATE',
        'http': 'PUT / PATCH',
        'orm': 'obj.field = ...; obj.save()',
        'meaning': 'Change one or more columns of an existing row.',
    },
    {
        'crud': 'DELETE',
        'sql': 'DELETE',
        'http': 'DELETE',
        'orm': 'obj.delete()',
        'meaning': 'Remove a row from the table permanently.',
    },
]

SCHEMA = [
    ('id', 'INTEGER', 'PRIMARY KEY, AUTOINCREMENT',
     'Row identifier, generated by the database.'),
    ('name', 'VARCHAR(100)', 'NOT NULL',
     "The student's full name."),
    ('email', 'VARCHAR(254)', 'NOT NULL, UNIQUE',
     'No two rows may share an email address.'),
    ('phone', 'VARCHAR(16)', 'NOT NULL, format-checked',
     '7 to 15 digits, with an optional leading "+".'),
]

#: The request/response path a single operation takes through Django, with the
#: file that handles each stage. The Simulation shows the same path per
#: operation, generated from `students/trace.py`.
REQUEST_FLOW = [
    ('Browser', '',
     'The student submits the HTML form, producing an HTTP request.'),
    ('URLconf', 'studentproject/urls.py',
     'Django matches the start of the path and <code>include()</code> hands the rest '
     'to the app that owns it.'),
    ('App URLs', 'students/urls.py',
     'The remaining path is matched against the app\'s patterns; the first match names '
     'the view to call.'),
    ('View', 'students/views.py',
     'The view builds a <code>StudentForm</code> from the submitted data.'),
    ('Form', 'students/forms.py',
     'Validation runs: field validators, then <code>clean_&lt;field&gt;()</code>, then '
     '<code>clean()</code>.'),
    ('Validators', 'students/validators.py',
     'The rules attached to the model fields run as part of that validation.'),
    ('Model / ORM', 'students/models.py',
     'If valid, <code>form.save()</code> asks the ORM to issue the SQL statement.'),
    ('Database', 'db.sqlite3',
     'The statement runs. Constraints such as UNIQUE may still refuse it. '
     '<strong>This is the only file whose contents change.</strong>'),
    ('Template', 'students/templates/students/',
     'The view renders a template with the result, which is returned to the browser.'),
]

# ---------------------------------------------------------------------------
# Procedure
# ---------------------------------------------------------------------------

PROCEDURE_STEPS = [
    ('Take the Pretest',
     'Answer the five questions in the Pretest section to check what you already know '
     'about CRUD and relational tables. Your score is recorded but does not affect '
     'anything else.'),
    ('Study the schema',
     'Open the Theory section and note the four columns of the <code>students</code> '
     'table, their types, and the constraints on each.'),
    ('Observe the initial state',
     'Open the Simulation section. The table shown is the live contents of the database. '
     'Press <strong>Run SELECT</strong> to issue a read with no filter.'),
    ('Perform each operation',
     'Work through CREATE, READ, UPDATE and DELETE using the controls on the simulator. '
     'After each one, read the SQL and ORM panels to see what the operation corresponds '
     'to.'),
    ('Test a constraint',
     'Deliberately insert a row whose email already exists. Observe that the database '
     'refuses it and that no row is added.'),
    ('Repeat the operations in the terminal',
     'Switch the Simulation page to <strong>Terminal mode</strong> and perform the same '
     'operations by typing them. Run each one in <strong>SQL</strong>, then switch to '
     '<strong>ORM</strong> and run the equivalent expression — the terminal prints the other '
     'form of every command, so you can compare them directly.'),
    ('Complete the Exercises',
     'The Exercises section lists seven tasks and marks each one complete automatically '
     'as you perform it — through the forms or in the terminal, either counts.'),
    ('Take the Posttest',
     'Answer the Posttest questions and compare your score with your pretest score.'),
    ('Leave feedback',
     'Tell us what was clear and what was not, using the Feedback section.'),
]

# ---------------------------------------------------------------------------
# References
# ---------------------------------------------------------------------------

REFERENCES = [
    {
        'title': 'Django documentation — Models and databases',
        'detail': 'The official reference for defining models, fields, constraints and '
                  'queries.',
        'url': 'https://docs.djangoproject.com/en/stable/topics/db/',
    },
    {
        'title': 'Django documentation — Working with forms',
        'detail': 'Form fields, validation order and the <code>clean_&lt;field&gt;()</code> '
                  'hooks used in this experiment.',
        'url': 'https://docs.djangoproject.com/en/stable/topics/forms/',
    },
    {
        'title': 'Django documentation — URL dispatcher',
        'detail': 'Path converters, <code>include()</code>, namespaces and named URL '
                  'patterns.',
        'url': 'https://docs.djangoproject.com/en/stable/topics/http/urls/',
    },
    {
        'title': 'Django REST Framework — Serializers',
        'detail': 'How serializers validate incoming JSON and render model instances.',
        'url': 'https://www.django-rest-framework.org/api-guide/serializers/',
    },
    {
        'title': 'SQLite — Query language reference',
        'detail': 'The SQL dialect used by the database behind this experiment.',
        'url': 'https://www.sqlite.org/lang.html',
    },
    {
        'title': 'Elmasri & Navathe, Fundamentals of Database Systems',
        'detail': 'Standard textbook treatment of the relational model, keys and '
                  'integrity constraints.',
        'url': '',
    },
]

# ---------------------------------------------------------------------------
# Contributors  >>> EDIT ME <<<
# ---------------------------------------------------------------------------

INSTITUTION = 'Your College Name, Department of Computer Engineering'

CONTRIBUTORS = [
    {
        'name': 'Student Name 1',
        'role': 'Developer — models, forms and validation',
        'affiliation': 'TE Computer Engineering',
    },
    {
        'name': 'Student Name 2',
        'role': 'Developer — simulator and templates',
        'affiliation': 'TE Computer Engineering',
    },
    {
        'name': 'Student Name 3',
        'role': 'Content — theory, case study and assessment',
        'affiliation': 'TE Computer Engineering',
    },
    {
        'name': 'Faculty Name',
        'role': 'Faculty mentor',
        'affiliation': 'Department of Computer Engineering',
    },
]
